server:
  port: 8108

spring:
  application:
    name: likes-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb.connectus.social:3308/like?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ssafyE106!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true


eureka:
  #  instance:
  #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka