server:
  port: 8081

spring:
  application:
    name: spot-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://spot.mariadb.connectus.social/spot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafyE106!
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

eureka:
  #  instance:
  #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka