server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: gather-service
            uri: http://localhost:8080/
            predicates:
              - Path=/gather/**
          - id: walk-service
            uri: http://localhost:8081/
            predicates:
              - Path=/walk/**
          - id: post-service
            uri: http://localhost:3001/
            predicates:
              - Path=/post/**
          - id: user-service
            uri: http://localhost:3007/
            predicates:
              - Path=/user/**
          - id: likes-service
            uri: http://localhost:3008/
            predicates:
              - Path=/likes/**
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver