server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: gather-service
          uri: http://localhost:8102/
          predicates:
            - Path=/gather/**
        - id: walk-service
          uri: http://localhost:8106/
          predicates:
            - Path=/walk/**
        - id: post-service
          uri: http://localhost:8101/
          predicates:
            - Path=/post/**
        - id: user-service
          uri: http://localhost:8107/
          predicates:
            - Path=/user/**
          filters:
            - name: CustomAuthFilter
              args:
                excludedFilterPathPattern: /user/(login|register)

        - id: likes-service
          uri: http://localhost:8108/
          predicates:
            - Path=/likes/**
        - id: event-service
          uri: http://localhost:8105/
          predicates:
            - Path=/event/**
        - id: spot-service
          uri: http://localhost:8103/
          predicates:
            - Path=/spot/**
    # default-filters:
    #     - name: CustomAuthFilter
    #       args:
    #         excludedFilterPathPattern: "http://localhost:3007/user/(login|register)"

jwt:
  secret-key: 9741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F79741AD2588AF89A25CBC596EA24F7

logging:
  level:
    org.springframework.cloud.gateway: trace
