server:
  port: 8761

spring:
  application:
    name: discovery-service
  datasource:
      url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false