server:
  port: 8761

spring:
  application:
    name: discovery-service
  datasource:
      url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ssafy
      password: ssafy
      driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false