server:
  port: 8761

spring:
  application:
    name: discovery-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb.connectus.social:3304/chat?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ssafyE106!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
