server:
  port: 8761

spring:
  application:
    name: discovery-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb.connectus.social:3304/chat?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ssafyE106!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      #      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /users/charming/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
