server:
  port: 8081

spring:
  application:
    name: walk-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://walk.mariadb.connectus.social:3306/post?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafyE106!
  jpa:
    hibernate:
      ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true


eureka:
  #  instance:
  #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka