server:
  port: 8081

spring:
  application:
    name: walk-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb.connectus.social:3306/walk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafyE106!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka