spring:
  application:
    name: connectus

  ## ??? microservice ?? datasource ??? ?????.
  datasource:
    url: jdbc:mariadb://${datasource.domain}:3306/connectus
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect