server:
  port: 8080

spring:
  application:
    name: gather-service
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: ssafy
#    password: ssafy
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://gather.mariadb.connectus.social:3306/gather?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafyE106!
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true


eureka:
  #  instance:
  #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka